[package]
name = "day11"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../util" }
clap = { version = "4.5.53", features = ["derive"] }
